/*
 * НТТ test task server API
 *
 * REST API для сервера в тестовом задании, основанное на OpenAPI 3.0-спецификации.  [Лариса Морожникова](https://t.me/l_milk)
 *
 * API version: 1.0.0
 * Contact: larisa.moroz@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FolderInfo struct {
	Id          int    `json:"id"`
	ParentId    *int   `json:"parent_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	HasNested   string `json:"has_nested"`
}
