/*
 * НТТ test task server API
 *
 * REST API для сервера в тестовом задании, основанное на OpenAPI 3.0-спецификации.  [Лариса Морожникова](https://t.me/l_milk)
 *
 * API version: 1.0.0
 * Contact: larisa.moroz@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"database/sql"
	"fmt"
	"github.com/gorilla/mux"
	"net/http"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc func(db *sql.DB, tablename string) http.HandlerFunc
}

type Routes []Route

func NewRouter(db *sql.DB, pgTableName string) *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc(db, pgTableName)
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(db *sql.DB, pgTableName string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Hello from HTT test task go API webserver!")
	}
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/api/v3/",
		Index,
	},

	Route{
		"FolderIdGet",
		"GET",
		"/api/v3/folder/{id}",
		FolderIdGet,
	},

	Route{
		"FoldersGetPost",
		"POST",
		"/api/v3/folders/get",
		FoldersGetPost,
	},

	Route{
		"FoldersTreeGet",
		"GET",
		"/api/v3/folders/tree",
		FoldersTreeGet,
	},
}
