openapi: 3.0.3
info:
  title: НТТ test task server API
  description: |-
    REST API для сервера в тестовом задании, основанное на OpenAPI 3.0-спецификации.

    [Лариса Морожникова](https://t.me/l_milk)
  contact:
    email: larisa.moroz@gmail.com
  version: 1.0.0
servers:
- url: http://localhost:8080/api/v3
tags:
- name: folders
  description: Получение списка папок
- name: folder
  description: Получение объекта одной папки
paths:
  /folders/get:
    post:
      tags:
      - folders
      summary: Список папок по указанному пути
      description: Путь передается в теле запроса в формате JSON как параметр `path`
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/folders_get_body'
        required: true
      responses:
        "200":
          description: успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Folders'
        "400":
          description: Invalid input
  /folders/tree:
    get:
      tags:
      - folders
      summary: Весь список папок для построения дерева
      responses:
        "200":
          description: успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Folders'
        "400":
          description: Invalid input
  /folder/{id}:
    get:
      tags:
      - folder
      summary: Описание папки
      description: В url указывается `id` папки
      parameters:
      - name: id
        in: path
        description: ID папки описание которой нужно выбрать
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FolderInfo'
        "400":
          description: Invalid input
components:
  schemas:
    Folders:
      type: array
      items:
        $ref: '#/components/schemas/FolderInfo'
      x-schema-name: Folders
    FolderInfo:
      required:
      - description
      - id
      - name
      - parent_id
      type: object
      properties:
        id:
          type: integer
          format: int64
        parent_id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
      example:
        parent_id: 6
        name: name
        description: description
        id: 0
      xml:
        name: address
    folders_get_body:
      type: object
      properties:
        path:
          type: string
          description: "Путь, по которому надо выбрать список вложенных папок"
